"""pine_export.py — J.26 — Export deployed genome as a TradingView Pine Script v5 study.

Lets the user see R's strategy live on TradingView charts. Doesn't trade — just
overlays entry/exit zones, SL/TP levels, gate state. Visual confirmation tool.

Output: dist/pine/R_<genome_id>.pine — paste into TradingView Pine editor.

Limitations:
- Pine v5 is simpler than MQL5 — only the most common genes mapped
- No multi-symbol logic (TradingView is single-symbol per chart)
- No actual trade execution (TV is a charting platform)
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

OUT_DIR = Path(r"C:\Users\Radhi\MT5\dist\pine")

PINE_TEMPLATE = '''//@version=5
// Generated by R Native — {symbol} {tf}
// Genome: {genome_id}  ·  PF: {pf}  ·  WR: {wr}%  ·  Trades: {trades}
// Generated: {generated_at}
strategy("R Native — {genome_id}", overlay=true,
         initial_capital=100, default_qty_type=strategy.fixed,
         default_qty_value=0.01, commission_type=strategy.commission.cash_per_order,
         commission_value=1.0)

// ── Genome params ──
sl_atr_mult       = input.float({sl_atr_mult}, "SL × ATR")
tp_atr_mult       = input.float({tp_atr_mult}, "TP × ATR")
start_hour        = input.int({start_hour},   "Session start hour (UTC)")
end_hour          = input.int({end_hour},     "Session end hour (UTC)")
rsi_period        = input.int({rsi_period},   "RSI period")
ema_fast          = input.int({ema_fast},     "EMA fast")
ema_slow          = input.int({ema_slow},     "EMA slow")
atr_period        = input.int({atr_period},   "ATR period")
breakout_lookback = input.int({breakout_lookback}, "Breakout lookback")

// ── Active gene flags ──
sig_breakout = {SIG_BREAKOUT}
sig_rsi      = {SIG_RSI}
sig_macd     = {SIG_MACD}
sig_engulfing = {SIG_ENGULFING}
sig_mom_break = {SIG_MOM_BREAK}
bias_rsi     = {BIAS_RSI}
bias_ema     = {BIAS_EMA}
bias_sma     = {BIAS_SMA}
filt_adx     = {FILT_ADX}
use_breakeven = {USE_BREAKEVEN}

// ── Indicators ──
rsi      = ta.rsi(close, rsi_period)
ema_f    = ta.ema(close, ema_fast)
ema_s    = ta.ema(close, ema_slow)
atr      = ta.atr(atr_period)
[diplus, diminus, adx] = ta.dmi(14, 14)

// ── Session window ──
in_session = hour(time, "UTC") >= start_hour and hour(time, "UTC") < end_hour

// ── Bias check ──
bias_ok = true
if bias_rsi
    bias_ok := rsi > 50
if bias_ema and bias_ok
    bias_ok := ema_f > ema_s
if filt_adx and adx < 20
    bias_ok := false

// ── Signals ──
buy_sig = false
sell_sig = false
if sig_rsi
    if rsi < 30
        buy_sig := true
    if rsi > 70
        sell_sig := true
if sig_breakout
    recent_high = ta.highest(high, breakout_lookback)[1]
    recent_low  = ta.lowest(low,  breakout_lookback)[1]
    if close > recent_high
        buy_sig := true
    if close < recent_low
        sell_sig := true
if sig_macd
    [macd_line, signal_line, _] = ta.macd(close, 12, 26, 9)
    if ta.crossover(macd_line, signal_line)
        buy_sig := true
    if ta.crossunder(macd_line, signal_line)
        sell_sig := true

// ── Entry ──
sl_dist = atr * sl_atr_mult
tp_dist = atr * tp_atr_mult
if buy_sig and bias_ok and in_session and strategy.position_size == 0
    strategy.entry("R_BUY", strategy.long)
    strategy.exit("R_BUY_EX", "R_BUY",
                  stop=close - sl_dist, limit=close + tp_dist)
if sell_sig and bias_ok and in_session and strategy.position_size == 0
    strategy.entry("R_SELL", strategy.short)
    strategy.exit("R_SELL_EX", "R_SELL",
                  stop=close + sl_dist, limit=close - tp_dist)

// ── Visualization ──
plot(ema_f, color=color.new(color.aqua, 50), title="EMA fast")
plot(ema_s, color=color.new(color.orange, 50), title="EMA slow")
plotshape(buy_sig and bias_ok and in_session, style=shape.triangleup,
          location=location.belowbar, color=color.green, size=size.small,
          title="R BUY signal")
plotshape(sell_sig and bias_ok and in_session, style=shape.triangledown,
          location=location.abovebar, color=color.red, size=size.small,
          title="R SELL signal")
bgcolor(in_session ? color.new(color.gray, 95) : na, title="Session")
'''


def _flag(active_genes: list, name: str) -> str:
    return "true" if name in active_genes else "false"


def generate_pine(symbol: str, genome_id: str, tf: str,
                  out_path: Path | None = None) -> Path:
    """Build a .pine file from a genome in the symbol vault."""
    cfg_path = Path(r"C:\Users\Radhi\MT5\data\r_native\symbol_configs") / f"{symbol}.json"
    if not cfg_path.exists():
        raise FileNotFoundError(f"no vault for {symbol}")
    cfg = json.loads(cfg_path.read_text(encoding="utf-8"))
    slim = next((s for s in cfg.get("ga_strategies", []) if s.get("id") == genome_id), None)
    if not slim:
        raise KeyError(f"{genome_id} not in vault")

    # Enrich with full record if available
    params = {}
    flags = {}
    active = slim.get("active_genes", [])
    src = (slim.get("source") or "").replace("GA_campaign_", "")
    if src:
        vf = Path(r"C:\Users\Radhi\MT5\data\r_native\campaigns") / src / "vault.json"
        if vf.exists():
            try:
                vault = json.loads(vf.read_text(encoding="utf-8"))
                full = next((r for r in vault
                             if r.get("genome", {}).get("id") == genome_id), None)
                if full:
                    params = full.get("genome", {}).get("params", {})
                    flags  = full.get("genome", {}).get("flags", {})
                    active = full.get("genome", {}).get("active_genes", active)
            except Exception: pass

    subs = {
        "genome_id":   genome_id,
        "symbol":      symbol,
        "tf":          tf,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "pf":          slim.get("profit_factor", 0),
        "wr":          slim.get("win_rate", 0),
        "trades":      slim.get("trades", 0),
        "sl_atr_mult": params.get("sl_atr_mult") or slim.get("sl_atr_mult") or 1.5,
        "tp_atr_mult": params.get("tp_atr_mult") or slim.get("tp_atr_mult") or 1.5,
        "start_hour":  params.get("start_hour") or slim.get("start_hour") or 0,
        "end_hour":    params.get("end_hour")   or slim.get("end_hour")   or 23,
        "rsi_period":  params.get("rsi_period", 14),
        "ema_fast":    params.get("ema_fast",   12),
        "ema_slow":    params.get("ema_slow",   26),
        "atr_period":  params.get("atr_period", 14),
        "breakout_lookback": params.get("breakout_lookback", 20),
        # Gene flags (Pine uses true/false)
        "SIG_BREAKOUT":  _flag(active, "use_sig_breakout"),
        "SIG_RSI":       _flag(active, "use_sig_rsi"),
        "SIG_MACD":      _flag(active, "use_sig_macd"),
        "SIG_ENGULFING": _flag(active, "use_sig_engulfing"),
        "SIG_MOM_BREAK": _flag(active, "use_sig_mom_break"),
        "BIAS_RSI":      _flag(active, "use_bias_rsi"),
        "BIAS_EMA":      _flag(active, "use_bias_ema"),
        "BIAS_SMA":      _flag(active, "use_bias_sma"),
        "FILT_ADX":      _flag(active, "use_filt_adx"),
        "USE_BREAKEVEN": _flag(active, "use_breakeven"),
    }
    rendered = PINE_TEMPLATE.format(**subs)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    out_path = out_path or (OUT_DIR / f"R_{genome_id}.pine")
    out_path.write_text(rendered, encoding="utf-8")
    return out_path


if __name__ == "__main__":
    import sys
    if len(sys.argv) < 4:
        print("usage: python -m r_native.pine_export <genome_id> <symbol> <tf>")
        sys.exit(1)
    p = generate_pine(sys.argv[2], sys.argv[1], sys.argv[3])
    print(f"✓ generated → {p}")
    print(f"  Paste into TradingView's Pine editor (https://www.tradingview.com/pine-editor/)")
